

INSERT INTO aeroports (nom, ville) VALUES
('Ndjili', 'Kinshasa'),
('Lubumbashi', 'Lubumbashi'),
('Goma', 'Goma'),
('Kalemie', 'Kalemie'),
('Kananga', 'Kananga'),
('Bangoka', 'Kisangani'),
('Bukavu Kavumu', 'Kamakombe'),
('Bunia', 'Bunia'),
('Kindu', 'Kindu'),
('Mbuji Mayi', 'Mbuji Mayi'),
('Ndolo', 'N''dolo'),
('Muanda', 'Muanda'),
('Beni', 'Beni'),
('Kolwezi', 'Kolwezi'),
('Kamina', 'Lumwe'),
('Wageni', 'Beni'),
('Gemena', 'Gemena'),
('Matari', 'Isiro'),
('Kikwit', 'Kikwit'),
('Mbandaka', 'Mbandaka'),
('Lodja', 'Lodja'),
('Tshimpi', 'Matadi'),
('Kamina City', 'Kamina'),
('Kisangani Simisini', NULL),
('Kabalo', 'Kabalo'),
('Kasongo', 'Kasongo'),
('Katale', 'Katale'),
('Katende', 'Katende'),
('Kimano Ii', 'Kimano Ii'),
('Kongolo', 'Kongolo'),
('Lokutu', 'Lokutu'),
('Manono', 'Manono'),
('Moba', 'Moba'),
('Moga', 'Moga'),
('Mulungu', 'Mulungu'),
('Mutoto', 'Mutoto'),
('Mwene-Ditu', 'Mwene-Ditu'),
('Punia', 'Punia'),
('Rutshuru', 'Rutshuru'),
('Sandoa', 'Sandoa'),
('Shabunda', 'Shabunda'),
('Bandundu', 'Bandundu'),
('Gbadolite', 'Gbadolite'),
('Boma Lukandu', 'Boma'),
('Buta Zega', 'Buta'),
('Lisala', 'Lisala'),
('Basankusu', 'Basankusu'),
('Boma', 'Boma'),
('Ilebo', 'Ilebo'),
('Inongo', 'Inongo'),
('Kiri', 'Kiri'),
('Nioki', 'Nioki'),
('Tshikapa', 'Tshikapa'),
('Tshumbe', 'Tshumbe'),
('Boende', 'Boende'),
('Tembo', NULL),
('Aba', 'Aba'),
('Abumumbazi', 'Abumumbazi'),
('Aketi', 'Aketi'),
('Ango', 'Ango'),
('Aru', 'Aru'),
('Bambili-Dingila', 'Bambili-Dingila'),
('Banga', 'Banga'),
('Banza Lute', 'Banza Lute'),
('Basengele', 'Basengele'),
('Basongo', 'Basongo'),
('Bau', 'Bau'),
('Bena-Dibele', 'Bena-Dibele'),
('Beno', 'Beno'),
('Beongo', 'Beongo'),
('Bibanga', 'Bibanga'),
('Bikoro', 'Bikoro'),
('Bindja', 'Bindja'),
('Binga', 'Binga'),
('Boeli Airstrip', 'Boeli'),
('Bokada', 'Bokada'),
('Bokela', 'Bokela'),
('Boko', 'Boko'),
('Bokoro', 'Bokoro'),
('Bokungu', 'Bokungu'),
('Bolila', 'Bolila'),
('Bolobo', 'Bolobo'),
('Bolongonkele', 'Bolongonkele'),
('Bondo', 'Bondo'),
('Bongimba', 'Bongimba'),
('Bonkita', 'Bonkita'),
('Boshwe', 'Boshwe'),
('Bosondjo', 'Bosondjo'),
('Boteka', 'Boteka'),
('Bukena', 'Bukena'),
('Bulape', 'Bulape'),
('Bulongo Kigogo', 'Bulongo Kigogo'),
('Bumba', 'Bumba'),
('Busala', 'Busala'),
('Rughenda Airfield', 'Butembo'),
('Celo Zongo', 'Celo Zongo'),
('Dakwa', 'Dakwa'),
('Dekese', 'Dekese'),
('Diboko', 'Diboko'),
('Dikungu', 'Dikungu'),
('Dilolo', 'Dilolo'),
('Dingele', 'Dingele'),
('Djokele', 'Djokele'),
('Djolu', 'Djolu'),
('Doko', 'Doko'),
('Doruma', 'Doruma'),
('Dungu-Uye', 'Dungu'),
('Dungu', 'Dungu'),
('Engengele', 'Engengele'),
('Epulu', 'Epulu'),
('Faradje', 'Faradje'),
('Fatundu', 'Fatundu'),
('Fungurume', 'Fungurume'),
('Gbado', 'Gbado'),
('Goyongo', 'Goyongo'),
('Gwaka', 'Gwaka'),
('Idiofa', 'Idiofa'),
('Idumbe', 'Idumbe'),
('Ikela', 'Ikela'),
('Imesse', 'Imesse'),
('Inga', 'Inga'),
('Ingende', 'Ingende'),
('Inkisi', 'Inkisi'),
('Ipeke', 'Ipeke'),
('Ipope Airstrip', 'Ipope'),
('Irebu', 'Irebu'),
('Ishango', 'Ishango'),
('Ishasha', 'Ishasha'),
('Isongo', 'Isongo'),
('Ito', 'Ito'),
('KM 95 CFL', 'Kabeta'),
('Tunta', 'Kabinda'),
('Kabombo', 'Kabombo'),
('Kabuba', 'Kabuba'),
('Kahemba', 'Kahemba'),
('Kailo', 'Kailo'),
('Kajiji', 'Kajiji'),
('Kala', 'Kala'),
('Kinkungwa', 'Kalima'),
('Kamisuku', 'Kalima'),
('Kalonda', 'Kalonda'),
('Kamatanda', 'Kamatanda'),
('Kamituga', 'Kamituga'),
('Kampene', 'Kampene'),
('Kanene', 'Kanene'),
('Kaniama', 'Kaniama'),
('Kansimba', 'Kansimba'),
('Kapanga', 'Kapanga'),
('Karawa', 'Karawa'),
('Kasaji', 'Kasaji'),
('Kasenga', 'Kasenga'),
('Kasese Kaniama', 'Kasese'),
('Kasese', 'Kasese'),
('Kashia', 'Kashia'),
('Kashobwe', 'Kashobwe'),
('Kasonga', 'Kasonga'),
('Kasongo-Lunda', 'Kasongo-Lunda'),
('Katako''kombe', 'Katako''kombe'),
('Katanda Rusthuru', 'Katanda Rusthuru'),
('Luvua', 'Katemesha'),
('Katubwe', 'Katubwe'),
('Katwe', 'Katwe'),
('Kempa', 'Kempa'),
('Kutu-Kempili', 'Kempili'),
('Kenge', 'Kenge'),
('Kere Kere', 'Kere Kere'),
('Kiapupe', 'Kiapupe'),
('Kibombo', 'Kibombo'),
('Kikongo Sur Wamba', 'Kikongo Sur Wamba'),
('Kilomines', 'Kilomines'),
('Kilwa', 'Kilwa'),
('Kimafu', 'Kimafu'),
('Kimbau', 'Kimbau'),
('Kimpangu', 'Kimpangu'),
('Kimpoko', 'Kimpoko'),
('Kipata Katika', 'Kipata Katika'),
('Kipushi', 'Kipushi'),
('Kisenge', 'Kisenge'),
('Kisengwa', 'Kisengwa'),
('Kitona', 'Kitona'),
('Kodoro', 'Kodoro'),
('Kole Sur Lukenie', 'Kole Sur Lukenie'),
('Kolokoso', 'Kolokoso'),
('Konde', 'Konde'),
('Kotakoli Airbase', 'Kotakoli'),
('Kutu-Ville', 'Kutu'),
('Kutusongo', 'Kutusongo'),
('Kwilu-Ngongo', 'Kwilu-Ngongo'),
('Libenge', 'Libenge'),
('Lodja Catholic Mission', 'Lodja'),
('Lombo', 'Lombo'),
('Lomela', 'Lomela'),
('Lubao', 'Lubao'),
('Lubero', 'Lubero'),
('Lubondaie', 'Lubondaie'),
('Lubondaie', 'Lubondaie'),
('Lubudi', 'Lubudi'),
('Luebo', 'Luebo'),
('Luena', 'Luena'),
('Lugushwa', 'Lugushwa'),
('Luheki', 'Luheki'),
('Luiza', 'Luiza'),
('Lukala', 'Lukala'),
('Lukombe-Batwa', 'Lukombe-Batwa'),
('Lulingu Tshionka', 'Lulingu Tshionka'),
('Luniemu', 'Luniemu'),
('Luozi', 'Luozi'),
('Lusambo', 'Lusambo'),
('Lusanga', 'Lusanga'),
('Lusinga', 'Lusinga'),
('Lutshatsha', 'Lutshatsha'),
('Mahagi', 'Mahagi'),
('Malanga', 'Malanga'),
('Malebo', 'Malebo'),
('Maluku Airstrip', 'Maluku'),
('Mambasa', 'Mambasa'),
('Mangai Ii', 'Mangai Ii'),
('Masamuna', 'Masamuna'),
('Masi Manimba', 'Masi Manimba'),
('Matari', 'Matari'),
('Mazelele', 'Mazelele'),
('Mboi', 'Mboi'),
('Mentole', 'Mentole'),
('Missayi', 'Missayi'),
('Mitwaba', 'Mitwaba'),
('Moanza', 'Moanza'),
('Mokaria-Yamoleka', 'Mokaria-Yamoleka'),
('Moma', 'Moma'),
('Mombongo', 'Mombongo'),
('Mondombe', 'Mondombe'),
('Monga', 'Monga'),
('Mongbwalu', 'Mongbwalu'),
('Mongo Wa Kenda', 'Mongo Wa Kenda'),
('Monieka', 'Monieka'),
('Monkoto', 'Monkoto'),
('Mpaka', 'Mpaka'),
('Muambi', 'Muambi'),
('Mukedi', 'Mukedi'),
('Mukoy', 'Mukoy'),
('Mulongo', 'Mulongo'),
('Mulungwishi', 'Mulungwishi'),
('Munkamba', 'Munkamba'),
('Musese', 'Musese'),
('Mushie', 'Mushie'),
('Mutena', 'Mutena'),
('Mutshatsha', 'Mutshatsha'),
('Mvula Sanda', 'Mvula Sanda'),
('Mwadingusha', 'Mwadingusha'),
('Mweka', 'Mweka'),
('N''Kolo-Fuma', 'N''Kolo-Fuma'),
('Nagero', 'Nagero'),
('Nebobongo', 'Nebobongo'),
('Ngandajika', 'Ngandajika'),
('Ngi', 'Ngi'),
('Ngumu', 'Ngumu'),
('Nia-Nia', 'Nia-Nia'),
('Nsangi', 'Nsangi'),
('Nyanga', 'Nyanga'),
('Nyankunde', 'Nyankunde'),
('Nyunzu', 'Nyunzu'),
('Nzamba', 'Nzamba'),
('Nzovu', 'Nzovu'),
('Obaye', 'Obaye'),
('Obokote', 'Obokote'),
('Oshwe', 'Oshwe'),
('Pelende', 'Pelende'),
('Pepa', 'Pepa'),
('Phibraki', 'Phibraki'),
('Pimu', 'Pimu'),
('Poko', 'Poko'),
('Popokabaka', 'Popokabaka'),
('Punia-Basenge', 'Punia-Basenge'),
('Former Pweto', 'Pweto'),
('Pweto', 'Pweto'),
('Rwindi', 'Rwindi'),
('Saulia', 'Saulia'),
('Semendwa', 'Semendwa'),
('Shongamba', 'Shongamba'),
('Sominka', 'Sominka'),
('Songa', 'Songa'),
('Tandala', 'Tandala'),
('Tingi-Tingi', 'Tingi-Tingi'),
('Tono', 'Tono'),
('Tshela', 'Tshela'),
('Tshibala', 'Tshibala'),
('Tshikaji', 'Tshikaji'),
('Tshimpumpu', 'Tshimpumpu'),
('Vanga', 'Vanga'),
('Wamba Luadi', 'Wamba Luadi'),
('Wasolo', 'Wasolo'),
('Watsa', 'Watsa'),
('Wema', 'Wema'),
('Wembo-Nyama', 'Wembo-Nyama'),
('Yakoma', 'Yakoma'),
('Yalingimba', 'Yalingimba'),
('Yangambi', 'Yangambi'),
('Yasa Bongo', 'Yasa Bongo'),
('Yedi', 'Yedi'),
('Yembe Moke', 'Yembe Moke'),
('Yemo', 'Yemo'),
('Yuki', 'Yuki'),
('Zaniwe', 'Zaniwe'),
('Isiro-Ville', 'Isiro'),
('Kamoa Mine Heliport', 'Kolwezi'),
('Mbulungu', 'Mbulungu');